### ISSUE TITLE
401 Missing credentials on every startup

### ISSUE THREAD

**Issue by Fatalution** [pypy-vrc/VRCX#127] opened 2020-12-21 16:19 UTC
Basically, title. I log in, close the VRCX, open it up again - and have to log in again. 
Is that the intended behavior?

**Comment by Natsumi-sama** [comment] 2020-12-21 16:30
I believe this is caused by your API key expiring, I'm currently in the process of creating a way to save your credentials so you don't have to type them in every time.

**Comment by Fatalution** [comment] 2020-12-21 16:32
> I believe this is caused by your API key expiring, I'm currently in the process of creating a way to save your credentials so you don't have to type them in every time.

Cool beans, thanks. I have also moved my VRCX to Program Files folder. Can that be causing some type of issue because of some accesses being borked? Should I move it somewhere else?

**Comment by Natsumi-sama** [comment] 2020-12-21 16:34
That shouldn't cause any permission problems but if it does you should be able to tell by your settings not saving after relaunching.

**Comment by Fusl** [comment] 2020-12-21 19:06
Feel free to upvote https://feedback.vrchat.com/feature-requests/p/allow-authcookie-to-be-used-from-a-different-ip-address-extra-features for VRChat to fix this issue on their side.

**Comment by Natsumi-sama** [comment] 2020-12-22 12:39
Hopefully this will do the trick but it will need some testing https://github.com/pypy-vrc/VRCX/pull/128

**Comment by Natsumi-sama** [comment] 2021-01-09 10:40
Should be fixed now if you tick save credentials and enable auto login in settings.

**Closed by Natsumi-sama** 2021-01-09 10:40 UTC
