### ISSUE TITLE
No longer see Location, OnPlayerJoined, and OnPlayerLeft entries in game log

### ISSUE THREAD

**Issue by Inverness** [pypy-vrc/VRCX#142] opened 2021-02-03 15:04 UTC
Since the VRChat update yesterday the Game Log tab no longer shows any new new Location, OnPlayerJoined, or OnPlayerLeft events.

The only new events I see are Notification events.

I also updated VRCX to version 20210130 at the same time, but I'm led to believe the issue is due to changes that were made to VRChat output logs.

**Comment by Natsumi-sama** [comment] 2021-02-03 15:51
Yup VRChat update changed the location/join/leave log entry format, it has already been fixed with these commits https://github.com/pypy-vrc/VRCX/commit/2c4b04f0be4aafe908e41bf5abcbaec237ff8584 https://github.com/pypy-vrc/VRCX/commit/3ded098322a0341460a0f859053a1441d5073db7 and will be in next release.

**Comment by Murkur** [comment] 2021-02-03 19:29
to ad onto this the gamelog watcher doesnt properly filter out user friend requests so it will show friend requests in game log
![image](https://user-images.githubusercontent.com/20288698/106798597-2e851580-662c-11eb-8c78-dc8d3b05c6e5.png)

**Comment by Murkur** [comment] 2021-02-03 23:14
also this comit doesnt fix showing your own location

**Comment by Natsumi-sama** [comment] 2021-02-04 01:04
It does fix own location, if you are building VRCX yourself make sure you update the entire source code. Game Log Notification isn't currently parsed so it can't be filter until/if that happens.

**Comment by Murkur** [comment] 2021-02-04 01:13
> It does fix own location, if you are building VRCX yourself make sure you update the entire source code. Game Log Notification isn't currently parsed so it can't be filter until/if that happens.

i have rebuilt it myself and also used last release and noticed a handful of bugs in stable release

**Comment by Natsumi-sama** [comment] 2021-02-04 01:25
What bugs did you have with the release build? it would be helpful if you could list them.

**Comment by Murkur** [comment] 2021-02-04 01:33
> if you have vr notifications off you cant change "when to display desktop notifications" setting
> vr wrist notifications don't work at all
> cant configure the button for vr wrist notifications in steamvr bindings "option gone completely"
> "when to display desktop notifications" settings for "desktop mode, game closed" don't work and will always spam notifications
> and the log watcher gamelog showing friend requests

**Comment by Natsumi-sama** [comment] 2021-02-04 01:52
1. Not a bug I haven't implemented support for that yet, requires moving a large amount of code around.
2. That should work fine if you have "SteamVR Overlay" enabled.
3. I never knew that worked with VRCX so I'm not sure about this one, Maybe this is related to 2 and your binding is broken in SteamVR.
4. I will look into it but I have had no such problems with it personally, works on my machine™.
5. As I said before this is working as intended, there is currently no support for interpreting Game Log Notifications.

**Comment by Murkur** [comment] 2021-02-04 02:05
1 alright
2 doesn't no clue why and old versions worked fine
3 its worked since first release
4 cheers
5 vrchat breakin shit as usual

**Closed** 2021-03-08 12:58 UTC
Labels: done
