### ISSUE TITLE
[Feature request] Notify if a friend is about to join the instance you're currently in

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#26] opened 2019-12-30 20:58 UTC

**Comment by Murkur** [comment] 2019-12-30 21:01
the notification of someone joining your instance is given as soon as the vrchat API can recognize it usually just as they nearly Finnish loading, vrchat API is not fast enough to make this possible reliably you would have to use a client that edits the game directly as you cant predict people joining you

**Comment by Murkur** [comment] 2019-12-30 21:03
> _No description provided._

your question is not detailed enough you get a notification on the steamvr hud in vrcx when a friend that is Favorited (is in a vrchat favorite group you have 3 to choose from) joins or comes online their name appears as yellow in the steamvr hud on your wrists aswell

**Comment by Fusl** [comment] 2019-12-31 04:15
The message that someone is joining an instance usually appears earlier on the hand overlay than the user can load the world data, initialize the world and then connect to the photon servers, so VRCX displaying a message, `XXX is about to join` before `XXX has joined` allows you to prepare up to 2 minutes before the user usually appears in the instance.

**Comment by pypy-vrc** [comment] 2019-12-31 08:30
VRCX is receiving friend-location in real time via WebSocket. this is the cause, so we can block it. Only if the friend's location is the same as my location.
If the friend's location is where I am, even without the API, it will be processed through the game log, so notifications will be displayed when actually joined (spawned).

**Comment by pypy-vrc** [comment] 2020-01-26 07:57
No more location information in real time, but only private, this problem seems to be solved i believe.

**Comment by Murkur** [comment] 2020-01-26 07:59
> No more location information in real time, but only private, this problem seems to be solved i believe.

I noticed that vrchat did a silent update on the webapi a few days ago to the way invites and instancing works as i use invite messaging to write to people as I cant speak they recently changed it so you cant send invite messages to people in privates our people outside of your current private world (as it gives your account a join token aka force invite if you know how to use it)

**Comment by pypy-vrc** [comment] 2020-01-26 09:29
> I noticed that vrchat did a silent update on the webapi a few days ago to the way invites and instancing works as i use invite messaging to write to people as I cant speak they recently changed it so you cant send invite messages to people in privates our people outside of your current private world (as it gives your account a join token aka force invite if you know how to use it)

As you know, you can't send an invite if your friend's status is busy. otherwise always sent. of course in my case it's really an instance invitation message, not invite messaging and doesn't matter if it's private.

**Comment by Fusl** [comment] 2020-03-12 04:03
@pypy-vrc Please reopen. VRChat broadcasting private instance as location on the Websocket stream seems to have been a bug that's mostly been fixed now, I think we can still make use of this feature, more importantly so because VRChat 2018 doesn't log player join events so this is the only way to tell when someone joined an instance.

`$username is joining` (new feature) and then `$username has joined` (existing join notification). In case the log file is faster in logging this before we get the info from the Websocket stream, we only display a join notification but omit the joining notification.

**Comment by Natsumi-sama** [comment] 2020-12-28 05:11
Closing because fixed.

**Closed by Natsumi-sama** 2020-12-28 05:11 UTC
