### ISSUE TITLE
Attack of the Robots

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#267] opened 2021-08-19 13:34 UTC
Is this an API endpoint issue or have they changed the way avatar images are called?  A lot of people (all having VRC+) only show avatars as robots (unknown avatar).  It seems to be inconsistent however.

**Comment by information-redacted** [comment] 2021-08-19 13:35
Hey, this is a dupe of #264 ^-^ might want to take a look there.

**Comment by Murkur** [comment] 2021-08-19 13:36
the api has changed anyone with VRCPlus no longer will have an avatar image shown [VRCX Discussion 264](https://github.com/pypy-vrc/VRCX/discussions/264)

**Comment by Murkur** [comment] 2021-08-19 13:36
> Hey, this is a dupe of #264 ^-^ might want to take a look there.

DAMNIT BEAT ME TO IT

**Comment by information-redacted** [comment] 2021-08-19 13:37
> > Hey, this is a dupe of #264 ^-^ might want to take a look there.
> 
> DAMNIT BEAT ME TO IT

:Hehe:

**Comment by GenesisAria** [comment] 2021-08-19 13:37
Ah, i looked through issues and didn't see anything, didn't think to look in discussions.

**Comment by Murkur** [comment] 2021-08-19 13:40
its fine the discussion will probably be closed so this may be considered the "original post" as its in the correct location (issues)

**Comment by Natsumi-sama** [comment] 2021-08-19 13:43
And for anyone that stumbles accross this, enable "Profile Picture Override" option in settings.

**Comment by fwenny** [comment] 2021-08-24 08:30
That still doesnt allow to check for avatars though, as they are all Unknown.

**Comment by Murkur** [comment] 2021-08-24 12:25
> That still doesnt allow to check for avatars though, as they are all Unknown.

Avatars Cannot be checked, avatars are checked by using the avatars image. no avatar image? no information.

**Closed** 2021-10-01 22:42 UTC
Labels: bug, done
